apiVersion: db.kubepostgres.dev/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: database-sample
    app.kubernetes.io/part-of: kubepostgres
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubepostgres
  name: database-sample
spec:
  containerImage: postgres
  volumeClaim:
    resources: {}
