name: CI

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout=3m

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.6.1

      - name: Run tests
        env:
          LOG_LEVEL: TRACE
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
